# Generated by Django 4.0 on 2022-01-31 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whattodo', models.CharField(default='', max_length=500)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
