# Generated by Django 4.0 on 2022-01-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todos',
            name='status',
        ),
        migrations.AddField(
            model_name='todos',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todos',
            name='whattodo',
            field=models.CharField(default='', max_length=500),
        ),
    ]
